# -*- coding: utf-8 -*-
"""dnacomp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnIazZxZ1i7UOByTKfXqUKyH7tphxkNJ
"""

import random
import pandas as pd

# Set up bases
bases = ['A', 'C', 'T']

# Generate random 12-nt sequence using only A, C, T
def generate_random_sequence(length=12):
    return ''.join(random.choice(bases) for _ in range(length))

# Check for forbidden patterns
def has_forbidden_patterns(seq):
    return 'AAAA' in seq or 'TTTT' in seq or 'CCCC' in seq

# Calculate Hamming distance between two sequences
def hamming_distance(seq1, seq2):
    return sum(c1 != c2 for c1, c2 in zip(seq1, seq2))

# Find longest common subsequence (dynamic programming version)
def longest_common_subsequence(seq1, seq2):
    m, n = len(seq1), len(seq2)
    dp = [[0]*(n+1) for _ in range(m+1)]
    result = 0
    for i in range(m):
        for j in range(n):
            if seq1[i] == seq2[j]:
                dp[i+1][j+1] = dp[i][j] + 1
                result = max(result, dp[i+1][j+1])
    return result

# Find number of same bases at same position
def same_base_positions(seq1, seq2):
    return sum(c1 == c2 for c1, c2 in zip(seq1, seq2))

# Generate a random initial library (small sample here)
library = [generate_random_sequence() for _ in range(300)]

# Create empty list for sequences that pass all filters
filtered_library = []

for seq in library:
    if has_forbidden_patterns(seq):
        continue
    valid = True
    for accepted_seq in filtered_library:
        if hamming_distance(seq, accepted_seq) <= 4:
            valid = False
            break
        if longest_common_subsequence(seq, accepted_seq) >= 8:
            valid = False
            break
        if same_base_positions(seq, accepted_seq) > 5:
            valid = False
            break
    if valid:
        filtered_library.append(seq)

# Show final sequences nicely
df = pd.DataFrame(filtered_library, columns=['DNA Sequence'])
print(df)

# Save to CSV if you want
df.to_csv('filtered_dna_library.csv', index=False)

import itertools
import pandas as pd

# Set up bases
bases = ['A', 'C', 'T']

# Check for forbidden patterns
def has_forbidden_patterns(seq):
    return 'AAAA' in seq or 'TTTT' in seq or 'CCC' in seq

# Calculate Hamming distance between two sequences
def hamming_distance(seq1, seq2):
    return sum(c1 != c2 for c1, c2 in zip(seq1, seq2))

# Find longest common subsequence (dynamic programming version)
def longest_common_subsequence(seq1, seq2):
    m, n = len(seq1), len(seq2)
    dp = [[0]*(n+1) for _ in range(m+1)]
    result = 0
    for i in range(m):
        for j in range(n):
            if seq1[i] == seq2[j]:
                dp[i+1][j+1] = dp[i][j] + 1
                result = max(result, dp[i+1][j+1])
    return result

# Find number of same bases at same position
def same_base_positions(seq1, seq2):
    return sum(c1 == c2 for c1, c2 in zip(seq1, seq2))

# Step 1: Generate all possible sequences (3^12)
all_sequences = [''.join(seq) for seq in itertools.product(bases, repeat=12)]

print(f"Generated {len(all_sequences)} sequences.")

# Step 2: Filter sequences based on forbidden patterns
initial_filtered = [seq for seq in all_sequences if not has_forbidden_patterns(seq)]

print(f"After forbidden pattern filtering: {len(initial_filtered)} sequences.")

# Step 3: Filter based on distance rules
final_library = []

for seq in initial_filtered:
    valid = True
    for accepted_seq in final_library:
        if hamming_distance(seq, accepted_seq) <= 4:
            valid = False
            break
        if longest_common_subsequence(seq, accepted_seq) >= 8:
            valid = False
            break
        if same_base_positions(seq, accepted_seq) > 5:
            valid = False
            break
    if valid:
        final_library.append(seq)

# Step 4: Show and/or save
df = pd.DataFrame(final_library, columns=['DNA Sequence'])
print(df)

# Save to CSV
df.to_csv('filtered_dna_library_full.csv', index=False)